version: '3.8'
services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped

volumes:
  data: 