version: '3.8'

services:
  followarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: followarr
    user: "${UID:-1000}:${GID:-1000}"  # Run as non-root user
    volumes:
      - ./data:/app/data:rw  # Persistent data storage
      - ./logs:/app/logs:rw  # Log files
      - ./config:/app/config:ro  # Configuration files (read-only)
    env_file:
      - .env
    ports:
      - "${WEBHOOK_PORT:-3000}:${WEBHOOK_PORT:-3000}"
    environment:
      - TZ=${TZ:-UTC}  # Set timezone
      - PYTHONUNBUFFERED=1  # Ensure Python output is unbuffered
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBHOOK_PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - followarr-net

networks:
  followarr-net:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local 