services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: followarr
    user: "${UID:-1000}:${GID:-1000}"  # Run as non-root user
    volumes:
      - ./data:/app/data:rw  # Explicit read-write permissions
      - ./logs:/app/logs:rw  # Add logging volume
    env_file:
      - .env
    ports:
      - "${WEBHOOK_SERVER_PORT:-3000}:${WEBHOOK_SERVER_PORT:-3000}"
    environment:
      - TZ=${TZ:-UTC}  # Set timezone
      - PYTHONUNBUFFERED=1  # Ensure Python output is unbuffered
      - PYTHONPATH=/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - followarr-net

networks:
  followarr-net:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local 